import {
  MoreHorizontal,
  MoreVertical,
  ShoppingCart,
  Check,
  Phone,
  Search,
  Star,
  Facebook,
  Instagram,
  MessageCircle,
  Headset,
  CircleUser,
  DiamondPercent,
  SlidersHorizontal,
  ChevronRight,
  ChevronLeft,
  LayoutGrid,
  LayoutList,
  Mail,
  ChartLine,
  Heart,
  MoveRight,
  MoveLeft,
  X,
  CircleX,
  SquarePen,
  MapPin,
  PhoneCall,
  LayoutDashboard,
  Clock,
  Folder,
  DollarSign,
  TrendingUp,
  TrendingDown,
  DollarSignIcon,
  Ticket,
  FileText,
  Users,
  ShieldCheck,
  ShoppingBag,
  List,
  PackagePlus,
  CreditCard,
  TicketPercent,
  FolderTree,
  MessageSquareShare,
  ShieldAlert,
  Settings,
  type LucideProps,
} from "lucide-react";

interface IconProps extends LucideProps {
  className?: string;
}
export const IconBundler = {
  MoreH: (props: IconProps) => <MoreHorizontal {...props} />,
  ShoppingBag: (props: IconProps) => <ShoppingBag {...props} />,
  Settings: (props: IconProps) => <Settings {...props} />,
  FolderTree: (props: IconProps) => <FolderTree {...props} />,
  MessageSquareShare: (props: IconProps) => <MessageSquareShare {...props} />,
  TicketPercent: (props: IconProps) => <TicketPercent {...props} />,
  FileText: (props: IconProps) => <FileText {...props} />,
  ShoppingCart: (props: IconProps) => <ShoppingCart {...props} />,
  ShieldCheck: (props: IconProps) => <ShieldCheck {...props} />,
  ShieldAlert: (props: IconProps) => <ShieldAlert {...props} />,
  List: (props: IconProps) => <List {...props} />,
  Users: (props: IconProps) => <Users {...props} />,
  Blog: (props: IconProps) => <FileText {...props} />,
  Coupon: (props: IconProps) => <Ticket {...props} />,
  CreditCard: (props: IconProps) => <CreditCard {...props} />,
  ShoppingOrOrder: (props: IconProps) => <ShoppingCart {...props} />,
  MoreV: (props: IconProps) => <MoreVertical {...props} />,
  Search: (props: IconProps) => <Search {...props} />,
  Cart: (props: IconProps) => <ShoppingCart {...props} />,
  Check: (props: IconProps) => <Check {...props} />,
  Phone: (props: IconProps) => <Phone {...props} />,
  Star: (props: IconProps) => <Star {...props} />,
  Facebook: (props: IconProps) => <Facebook {...props} />,
  Instagram: (props: IconProps) => <Instagram {...props} />,
  Message: (props: IconProps) => <MessageCircle {...props} />,
  Support: (props: IconProps) => <Headset {...props} />,
  CircleUser: (props: IconProps) => <CircleUser {...props} />,
  Saving: (props: IconProps) => <DiamondPercent {...props} />,
  SliderH: (props: IconProps) => <SlidersHorizontal {...props} />,
  RightArrow: (props: IconProps) => <ChevronRight {...props} />,
  LeftArrow: (props: IconProps) => <ChevronLeft {...props} />,
  ListLayout: (props: IconProps) => <LayoutList {...props} />,
  GridLayout: (props: IconProps) => <LayoutGrid {...props} />,
  Cancle: (props: IconProps) => <X {...props} />,
  Heart: (props: IconProps) => <Heart {...props} />,
  Mail: (props: IconProps) => <Mail {...props} />,
  Chart: (props: IconProps) => <ChartLine {...props} />,
  MoveR: (props: IconProps) => <MoveRight {...props} />,
  MoveL: (props: IconProps) => <MoveLeft {...props} />,
  Clock: (props: IconProps) => <Clock {...props} />,
  Location: (props: IconProps) => <MapPin {...props} />,
  Call: (props: IconProps) => <PhoneCall {...props} />,
  EditPen: (props: IconProps) => <SquarePen {...props} />,
  CancleRound: (props: IconProps) => <CircleX {...props} />,
  LayoutDashboard: (props: IconProps) => <LayoutDashboard {...props} />,
  DollarSign: (props: IconProps) => <DollarSign {...props} />,
  Folder: (props: IconProps) => <Folder {...props} />,
  TrendingDown: (props: IconProps) => <TrendingDown {...props} />,
  TrendingUp: (props: IconProps) => <TrendingUp {...props} />,
  Dollar: (props: IconProps) => <DollarSignIcon {...props} />,
};
