import type { ColumnDef } from "@tanstack/react-table";
type UserRole = "user" | "admin" | "fake";
export interface IUser {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  cartItemCount: number;
  lastPurchasedItem: string;
  totalPurchaseCount: number;
  createdAt?: string | Date;
  isAccountActive: boolean;
}

export const userData: IUser[] = [
  {
    id: "u-001",
    name: "Kazi Mehedi",
    email: "mehedi@example.com",
    role: "admin",
    cartItemCount: 5,
    lastPurchasedItem: "Logitech MX Master 3S",
    totalPurchaseCount: 12,
    isAccountActive: true,
    createdAt: "2024-01-15",
  },
  {
    id: "u-002",
    name: "Ariful Islam",
    email: "arif@techghar.com",
    role: "user",
    cartItemCount: 2,
    lastPurchasedItem: "Keychron K2 Keyboard",
    totalPurchaseCount: 8,
    isAccountActive: true,
    createdAt: "2024-02-10",
  },
  {
    id: "u-003",
    name: "Sumaiya Khan",
    email: "sumaiya@gmail.com",
    role: "user",
    cartItemCount: 0,
    lastPurchasedItem: "Sony WH-1000XM5",
    totalPurchaseCount: 3,
    isAccountActive: false,
    createdAt: "2023-11-20",
  },
  {
    id: "u-004",
    name: "Tanvir Ahmed",
    email: "tanvir@outlook.com",
    role: "fake",
    cartItemCount: 8,
    lastPurchasedItem: "Dell UltraSharp 27",
    totalPurchaseCount: 15,
    isAccountActive: true,
    createdAt: "2024-01-05",
  },
  {
    id: "u-005",
    name: "Sajid Hossain",
    email: "sajid@example.com",
    role: "user",
    cartItemCount: 1,
    lastPurchasedItem: "TP-Link Archer AX73",
    totalPurchaseCount: 2,
    isAccountActive: true,
    createdAt: "2024-03-01",
  },
  {
    id: "u-006",
    name: "Nusrat Jahan",
    email: "nusrat@yahoo.com",
    role: "user",
    cartItemCount: 12,
    lastPurchasedItem: "iPad Air M2",
    totalPurchaseCount: 5,
    isAccountActive: true,
    createdAt: "2023-12-12",
  },
  {
    id: "u-007",
    name: "Rakib Hassan",
    email: "rakib@domain.com",
    role: "fake",
    cartItemCount: 0,
    lastPurchasedItem: "Generic USB Cable",
    totalPurchaseCount: 1,
    isAccountActive: false,
    createdAt: "2024-02-28",
  },
  {
    id: "u-008",
    name: "Ayesha Siddiqua",
    email: "ayesha@example.com",
    role: "user",
    cartItemCount: 4,
    lastPurchasedItem: "Samsung T7 SSD",
    totalPurchaseCount: 9,
    isAccountActive: true,
    createdAt: "2024-01-22",
  },
  {
    id: "u-009",
    name: "Fahim Shahriar",
    email: "fahim@techghar.com",
    role: "admin",
    cartItemCount: 6,
    lastPurchasedItem: "MacBook Pro M3",
    totalPurchaseCount: 22,
    isAccountActive: true,
    createdAt: "2023-10-15",
  },
  {
    id: "u-010",
    name: "Mahmudul Hasan",
    email: "mahmud@gmail.com",
    role: "user",
    cartItemCount: 3,
    lastPurchasedItem: "Razer DeathAdder V3",
    totalPurchaseCount: 4,
    isAccountActive: true,
    createdAt: "2024-02-05",
  },
  {
    id: "u-011",
    name: "Rifat Bin Azad",
    email: "rifat@example.com",
    role: "user",
    cartItemCount: 9,
    lastPurchasedItem: "Elgato Wave:3",
    totalPurchaseCount: 6,
    isAccountActive: true,
    createdAt: "2024-01-30",
  },
  {
    id: "u-012",
    name: "Sadia Afrin",
    email: "sadia@outlook.com",
    role: "user",
    cartItemCount: 2,
    lastPurchasedItem: "HyperX Cloud II",
    totalPurchaseCount: 11,
    isAccountActive: true,
    createdAt: "2024-02-14",
  },
  {
    id: "u-013",
    name: "Imtiaz Ahmed",
    email: "imtiaz@tech.com",
    role: "fake",
    cartItemCount: 5,
    lastPurchasedItem: "Secretlab Titan Evo",
    totalPurchaseCount: 18,
    isAccountActive: true,
    createdAt: "2023-09-25",
  },
  {
    id: "u-014",
    name: "Farhana Yasmin",
    email: "farhana@yahoo.com",
    role: "user",
    cartItemCount: 15,
    lastPurchasedItem: "Apple Watch Series 9",
    totalPurchaseCount: 7,
    isAccountActive: true,
    createdAt: "2024-01-18",
  },
  {
    id: "u-015",
    name: "Jasim Uddin",
    email: "jasim@gmail.com",
    role: "fake",
    cartItemCount: 0,
    lastPurchasedItem: "N/A",
    totalPurchaseCount: 0,
    isAccountActive: false,
    createdAt: "2024-03-10",
  },
  {
    id: "u-016",
    name: "Kamrul Hasan",
    email: "kamrul@domain.com",
    role: "user",
    cartItemCount: 7,
    lastPurchasedItem: "HDMI 2.1 Cable",
    totalPurchaseCount: 13,
    isAccountActive: true,
    createdAt: "2024-02-20",
  },
  {
    id: "u-017",
    name: "Laila Arjumand",
    email: "laila@example.com",
    role: "admin",
    cartItemCount: 4,
    lastPurchasedItem: "ASUS ROG Swift",
    totalPurchaseCount: 25,
    isAccountActive: true,
    createdAt: "2023-08-12",
  },
  {
    id: "u-018",
    name: "Mominul Haque",
    email: "momin@outlook.com",
    role: "user",
    cartItemCount: 2,
    lastPurchasedItem: "Wacom Intuos Pro",
    totalPurchaseCount: 4,
    isAccountActive: true,
    createdAt: "2024-01-11",
  },
  {
    id: "u-019",
    name: "Nazmul Huda",
    email: "nazmul@gmail.com",
    role: "user",
    cartItemCount: 11,
    lastPurchasedItem: "WD Black 4TB HDD",
    totalPurchaseCount: 9,
    isAccountActive: true,
    createdAt: "2024-02-01",
  },
  {
    id: "u-020",
    name: "Oishi Rahman",
    email: "oishi@yahoo.com",
    role: "user",
    cartItemCount: 6,
    lastPurchasedItem: "BenQ ScreenBar",
    totalPurchaseCount: 6,
    isAccountActive: true,
    createdAt: "2024-02-18",
  },
  {
    id: "u-021",
    name: "Pritom Kundu",
    email: "pritom@example.com",
    role: "user",
    cartItemCount: 3,
    lastPurchasedItem: "Ubiquiti UniFi AP",
    totalPurchaseCount: 5,
    isAccountActive: true,
    createdAt: "2024-01-25",
  },
  {
    id: "u-022",
    name: "Quazi Arif",
    email: "quazi@tech.com",
    role: "fake",
    cartItemCount: 1,
    lastPurchasedItem: "Sonos Beam Gen 2",
    totalPurchaseCount: 14,
    isAccountActive: true,
    createdAt: "2023-12-05",
  },
  {
    id: "u-023",
    name: "Raisa Islam",
    email: "raisa@gmail.com",
    role: "user",
    cartItemCount: 9,
    lastPurchasedItem: "Kindle Paperwhite",
    totalPurchaseCount: 3,
    isAccountActive: true,
    createdAt: "2024-02-22",
  },
  {
    id: "u-024",
    name: "Sabbir Rahman",
    email: "sabbir@outlook.com",
    role: "user",
    cartItemCount: 4,
    lastPurchasedItem: "Elgato HD60 X",
    totalPurchaseCount: 6,
    isAccountActive: true,
    createdAt: "2024-01-14",
  },
  {
    id: "u-025",
    name: "Tasnim Sultana",
    email: "tasnim@yahoo.com",
    role: "user",
    cartItemCount: 8,
    lastPurchasedItem: "Noctua NH-D15",
    totalPurchaseCount: 7,
    isAccountActive: true,
    createdAt: "2024-02-09",
  },
  {
    id: "u-026",
    name: "Utpal Das",
    email: "utpal@example.com",
    role: "user",
    cartItemCount: 13,
    lastPurchasedItem: "Intel Core i9-14900K",
    totalPurchaseCount: 4,
    isAccountActive: true,
    createdAt: "2024-01-08",
  },
  {
    id: "u-027",
    name: "Viola Gomez",
    email: "viola@techghar.com",
    role: "admin",
    cartItemCount: 5,
    lastPurchasedItem: "NVIDIA RTX 4090",
    totalPurchaseCount: 30,
    isAccountActive: true,
    createdAt: "2023-07-20",
  },
  {
    id: "u-028",
    name: "Wahid Murad",
    email: "wahid@gmail.com",
    role: "user",
    cartItemCount: 2,
    lastPurchasedItem: "NZXT H9 Flow",
    totalPurchaseCount: 2,
    isAccountActive: true,
    createdAt: "2024-02-27",
  },
  {
    id: "u-029",
    name: "Xavier Rozario",
    email: "xavier@outlook.com",
    role: "fake",
    cartItemCount: 0,
    lastPurchasedItem: "Unknown",
    totalPurchaseCount: 0,
    isAccountActive: false,
    createdAt: "2024-03-05",
  },
  {
    id: "u-030",
    name: "Yasin Ali",
    email: "yasin@yahoo.com",
    role: "user",
    cartItemCount: 7,
    lastPurchasedItem: "Lian Li SL120 Fans",
    totalPurchaseCount: 10,
    isAccountActive: true,
    createdAt: "2024-02-11",
  },
  {
    id: "u-031",
    name: "Zubair Talukder",
    email: "zubair@example.com",
    role: "fake",
    cartItemCount: 4,
    lastPurchasedItem: "Meta Quest 3",
    totalPurchaseCount: 12,
    isAccountActive: true,
    createdAt: "2023-11-15",
  },
  {
    id: "u-032",
    name: "Anika Tabassum",
    email: "anika@gmail.com",
    role: "user",
    cartItemCount: 10,
    lastPurchasedItem: "Thrustmaster T300RS",
    totalPurchaseCount: 5,
    isAccountActive: true,
    createdAt: "2024-02-03",
  },
  {
    id: "u-033",
    name: "Bishwajit Roy",
    email: "bishu@outlook.com",
    role: "user",
    cartItemCount: 3,
    lastPurchasedItem: "DisplayPort 1.4 Cable",
    totalPurchaseCount: 3,
    isAccountActive: true,
    createdAt: "2024-01-28",
  },
  {
    id: "u-034",
    name: "Chanchal Chowdhury",
    email: "chanchal@yahoo.com",
    role: "user",
    cartItemCount: 6,
    lastPurchasedItem: "Epson EcoTank L3210",
    totalPurchaseCount: 7,
    isAccountActive: true,
    createdAt: "2024-02-15",
  },
  {
    id: "u-035",
    name: "Dipa Karmakar",
    email: "dipa@techghar.com",
    role: "admin",
    cartItemCount: 2,
    lastPurchasedItem: "Brother HL-L2350DW",
    totalPurchaseCount: 19,
    isAccountActive: true,
    createdAt: "2023-10-10",
  },
  {
    id: "u-036",
    name: "Emon Ahmed",
    email: "emon@gmail.com",
    role: "user",
    cartItemCount: 11,
    lastPurchasedItem: "Fujitsu ScanSnap iX1600",
    totalPurchaseCount: 4,
    isAccountActive: true,
    createdAt: "2024-02-07",
  },
  {
    id: "u-037",
    name: "Faruk Hossain",
    email: "faruk@outlook.com",
    role: "user",
    cartItemCount: 5,
    lastPurchasedItem: "APC Pro GX 1500VA",
    totalPurchaseCount: 8,
    isAccountActive: true,
    createdAt: "2024-01-19",
  },
  {
    id: "u-038",
    name: "Gias Uddin",
    email: "gias@yahoo.com",
    role: "user",
    cartItemCount: 1,
    lastPurchasedItem: "MSI MAG Z790 Tomahawk",
    totalPurchaseCount: 6,
    isAccountActive: true,
    createdAt: "2024-02-12",
  },
  {
    id: "u-039",
    name: "Habiba Khatun",
    email: "habiba@example.com",
    role: "fake",
    cartItemCount: 8,
    lastPurchasedItem: "Crucial P5 Plus 2TB",
    totalPurchaseCount: 22,
    isAccountActive: true,
    createdAt: "2023-09-15",
  },
  {
    id: "u-040",
    name: "Ishtiaq Ahmed",
    email: "ishtiaq@gmail.com",
    role: "user",
    cartItemCount: 4,
    lastPurchasedItem: "Lian Li GB-001 Bracket",
    totalPurchaseCount: 5,
    isAccountActive: true,
    createdAt: "2024-02-25",
  },
  {
    id: "u-041",
    name: "Junaid Jamshed",
    email: "junaid@outlook.com",
    role: "user",
    cartItemCount: 14,
    lastPurchasedItem: "SanDisk Extreme Pro",
    totalPurchaseCount: 8,
    isAccountActive: true,
    createdAt: "2024-01-07",
  },
  {
    id: "u-042",
    name: "Khadija Begum",
    email: "khadija@yahoo.com",
    role: "user",
    cartItemCount: 2,
    lastPurchasedItem: "Intel Wi-Fi 6E AX210",
    totalPurchaseCount: 11,
    isAccountActive: true,
    createdAt: "2024-02-17",
  },
  {
    id: "u-043",
    name: "Liton Das",
    email: "liton@techghar.com",
    role: "admin",
    cartItemCount: 6,
    lastPurchasedItem: "Samsung Odyssey G9",
    totalPurchaseCount: 16,
    isAccountActive: true,
    createdAt: "2023-12-20",
  },
  {
    id: "u-044",
    name: "Mezbah Uddin",
    email: "mezbah@gmail.com",
    role: "user",
    cartItemCount: 3,
    lastPurchasedItem: "GMK+ Laser Keycaps",
    totalPurchaseCount: 4,
    isAccountActive: true,
    createdAt: "2024-02-13",
  },
  {
    id: "u-045",
    name: "Niaz Morshed",
    email: "niaz@outlook.com",
    role: "user",
    cartItemCount: 9,
    lastPurchasedItem: "Zowie CAMADE II",
    totalPurchaseCount: 7,
    isAccountActive: true,
    createdAt: "2024-01-28",
  },
  {
    id: "u-046",
    name: "Onik Islam",
    email: "onik@yahoo.com",
    role: "user",
    cartItemCount: 5,
    lastPurchasedItem: "Stream Deck MK.2",
    totalPurchaseCount: 3,
    isAccountActive: true,
    createdAt: "2024-02-09",
  },
  {
    id: "u-047",
    name: "Pavel Rahman",
    email: "pavel@example.com",
    role: "fake",
    cartItemCount: 7,
    lastPurchasedItem: "SteelSeries QcK Prism",
    totalPurchaseCount: 13,
    isAccountActive: true,
    createdAt: "2023-11-28",
  },
  {
    id: "u-048",
    name: "Rina Akter",
    email: "rina@gmail.com",
    role: "user",
    cartItemCount: 0,
    lastPurchasedItem: "Ugreen Phone Stand",
    totalPurchaseCount: 6,
    isAccountActive: true,
    createdAt: "2024-02-21",
  },
  {
    id: "u-049",
    name: "Siam Ahmed",
    email: "siam@outlook.com",
    role: "user",
    cartItemCount: 12,
    lastPurchasedItem: "iFixit Pro Tech Toolkit",
    totalPurchaseCount: 2,
    isAccountActive: true,
    createdAt: "2024-01-05",
  },
  {
    id: "u-050",
    name: "Tania Akter",
    email: "tania@techghar.com",
    role: "admin",
    cartItemCount: 4,
    lastPurchasedItem: "Cisco Business 250",
    totalPurchaseCount: 25,
    isAccountActive: true,
    createdAt: "2023-08-15",
  },
]; 

export const columns: ColumnDef<IUser>[] = [
  {
    accessorKey: "name",
    header: () => <div className="text-left">Name</div>,
    // cell: ({ row }) => <div className="text-left">{row.getValue("name")}</div>,
  },
  {
    accessorKey: "email",
    header: () => <div className="text-left">Email</div>,
  },
  {
    accessorKey: "cartItemCount",
    header: () => <div className="text-left">Cart</div>,
  },
  {
    accessorKey: "role",
    header: () => <div className="text-left">Role</div>,
  },
  {
    accessorKey: "lastPurchasedItem",
    header: () => <div className="text-left">Last Purchased</div>,
  },
  {
    accessorKey: "totalPurchaseCount",
    header: () => <div className="text-left">Total</div>,
  },
  {
    accessorKey: "isAccountActive",
    header: () => <div className="text-left">Active</div>,
  },
];
